site_name: Battlebound Tactics
theme:
  name: ivory
  favicon: resources/logo.ico


nav:
  - ğŸ  PresentaciÃ³n: index.md
  - ğŸ“¦ Modelos del Proyecto: modelos.md
  - ğŸ–¥ï¸ Vistas de Django: vistas.md
  - âš”ï¸ LÃ³gica del combate: logica-combate.md
  - ğŸ§  MÃ³dulos de core/:
      - Jugador: core-jugador.md
      - Enemigos: core-enemigos.md
      - Efectos: core-efectos.md
      - EstadÃ­sticas: core-estadisticas.md
      - Probabilidades: core-probabilidades.md
      - Utilidades de Combate: core-utils-combate.md
      - ResoluciÃ³n de Turnos: core-utils-resolvedor.md
  - ğŸ§© API y Endpoints Externos: api.md
  - ğŸš€ Despliegue y ConfiguraciÃ³n: despliegue.md
  - ğŸ§¾ Conclusiones: conclusiones.md

# ConfiguraciÃ³n adicional opcional
site_description: "DocumentaciÃ³n oficial de Battlebound Tactics"
site_author: Jonatan GarcÃ­a Luna
repo_url: https://github.com/JonatanGarLun/proyecto-DAW
edit_uri: ""

markdown_extensions:
  - toc:
      permalink: true
  - footnotes
  - tables
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight